#!/usr/bin/env python3
import os
import subprocess

################ Git Scripts ###################
branch = 'master'
commit_massage = 'C-Printf'

#run the git and the push command
subprocess.run(['git','add','.'])
subprocess.run(['git','commit','-m',commit_massage])
subprocess.run(['git','push'])
